version: v.2.3.4
pidfile: ./jobserver.pid
retrystartup: true
useserverconfig: true
cluster:
  hosts: 127.0.0.1:2181
  root: /cloudtask
  pulse: 30s
  timeout: 60s
  threshold: 1
api:
  hosts: [":8985"]
  enablecors: true
scheduler:
  allocmode: hash
  allocrecovery: 320s
cache:
  lrusize: 1024
  storagedriver:
      mongo:
        hosts: 127.0.0.1:27017
        database: cloudtask
        auth: {
         user: ,
         password:  
        }
notifications:
    endpoints:
      - name: smtp
        host: smtp.example.com
        port: 25
        user:
        password:
        sender: cloudtask@example.com
        enabled: true
logger:
    logfile: ./logs/jobserver.log
    loglevel: error
    logsize: 20971520
...
